// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/proto/node_stream.proto

package schedulerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeStateEvent carries one node's heartbeat from the scheduler replica that
// received it to the replicas that did not.
//
// A node's connection to the scheduler is sticky: kube-proxy binds it to one
// replica for the life of the TCP connection, so with N replicas each hears
// from roughly 1/N of the fleet and would place blind on the rest. The replica
// that took the heartbeat republishes it, and every replica converges on the
// whole fleet's liveness and capacity without the node knowing there is more
// than one scheduler.
type NodeStateEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which replica published this, so a replica skips its own echo.
	OriginReplicaId string `protobuf:"bytes,1,opt,name=origin_replica_id,json=originReplicaId,proto3" json:"origin_replica_id,omitempty"`
	// When the publishing replica saw the heartbeat, on its own clock.
	//
	// Applied verbatim rather than restamped on arrival: a stream that backs up
	// would otherwise make every node look freshly seen and disable the health
	// gate across the fleet. Replica clocks are compared against each other
	// here, never against a node's.
	LastSeenUnixMs int64 `protobuf:"varint,2,opt,name=last_seen_unix_ms,json=lastSeenUnixMs,proto3" json:"last_seen_unix_ms,omitempty"`
	// The heartbeat as received, minus everything that belongs to the one
	// replica that took the RPC: the roster and its digest, and the emitted
	// event count. Roster reconciliation has a single writer per node by
	// design, and republishing rosters would make this stream O(sandboxes).
	Heartbeat     *HeartbeatRequest `protobuf:"bytes,3,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStateEvent) Reset() {
	*x = NodeStateEvent{}
	mi := &file_api_proto_node_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStateEvent) ProtoMessage() {}

func (x *NodeStateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStateEvent.ProtoReflect.Descriptor instead.
func (*NodeStateEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_node_stream_proto_rawDescGZIP(), []int{0}
}

func (x *NodeStateEvent) GetOriginReplicaId() string {
	if x != nil {
		return x.OriginReplicaId
	}
	return ""
}

func (x *NodeStateEvent) GetLastSeenUnixMs() int64 {
	if x != nil {
		return x.LastSeenUnixMs
	}
	return 0
}

func (x *NodeStateEvent) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		return x.Heartbeat
	}
	return nil
}

var File_api_proto_node_stream_proto protoreflect.FileDescriptor

const file_api_proto_node_stream_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/node_stream.proto\x12\fscheduler.v1\x1a\x19api/proto/scheduler.proto\"\xb1\x01\n" +
	"\x0eNodeStateEvent\x12*\n" +
	"\x11origin_replica_id\x18\x01 \x01(\tR\x0foriginReplicaId\x12)\n" +
	"\x11last_seen_unix_ms\x18\x02 \x01(\x03R\x0elastSeenUnixMs\x12<\n" +
	"\theartbeat\x18\x03 \x01(\v2\x1e.scheduler.v1.HeartbeatRequestR\theartbeatJ\x04\b\x04\x10\x05J\x04\b\x05\x10\x06B)Z'agentenv/services/api/proto;schedulerv1b\x06proto3"

var (
	file_api_proto_node_stream_proto_rawDescOnce sync.Once
	file_api_proto_node_stream_proto_rawDescData []byte
)

func file_api_proto_node_stream_proto_rawDescGZIP() []byte {
	file_api_proto_node_stream_proto_rawDescOnce.Do(func() {
		file_api_proto_node_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_node_stream_proto_rawDesc), len(file_api_proto_node_stream_proto_rawDesc)))
	})
	return file_api_proto_node_stream_proto_rawDescData
}

var file_api_proto_node_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_node_stream_proto_goTypes = []any{
	(*NodeStateEvent)(nil),   // 0: scheduler.v1.NodeStateEvent
	(*HeartbeatRequest)(nil), // 1: scheduler.v1.HeartbeatRequest
}
var file_api_proto_node_stream_proto_depIdxs = []int32{
	1, // 0: scheduler.v1.NodeStateEvent.heartbeat:type_name -> scheduler.v1.HeartbeatRequest
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_node_stream_proto_init() }
func file_api_proto_node_stream_proto_init() {
	if File_api_proto_node_stream_proto != nil {
		return
	}
	file_api_proto_scheduler_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_node_stream_proto_rawDesc), len(file_api_proto_node_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_node_stream_proto_goTypes,
		DependencyIndexes: file_api_proto_node_stream_proto_depIdxs,
		MessageInfos:      file_api_proto_node_stream_proto_msgTypes,
	}.Build()
	File_api_proto_node_stream_proto = out.File
	file_api_proto_node_stream_proto_goTypes = nil
	file_api_proto_node_stream_proto_depIdxs = nil
}
